search_task:
  description: >
    -You are the Search Agent in system
    -You need to search {user_query} for factual answers.
    -Your role is to respond user queries requiring factual, contexual answers from web search using serper dev tool.

    ***Capabiliteies & Tools***
    **serper_dev_tool**: use serper_dev_tool to obtain external, potentially real world information.
  expected_output: >
    Synthesized response got from the SearchAgent
  agent: search

